name: devunity
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
    repo: nurdjedidi/devunity
  build_command: npm install && npm run build
  run_command: npm run start
  envs:
  - key: NODE_ENV
    value: production 