name: devunity
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
    repo: nurdjedidi/devunity
  buildpacks:
    - name: digitalocean/nodejs-appdetect
      version: v0.0.6
  build_command: |
    npm install @rollup/rollup-linux-x64-gnu@4.9.5 --platform=linux --arch=x64
    npm install --legacy-peer-deps
    npm run build
  run_command: |
    echo "Starting server..."
    NODE_ENV=production node .output/server/index.mjs
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: 8080
  - key: DB_HOST
    value: ${DB_HOST}
  - key: DB_USER
    value: ${DB_USER}
  - key: DB_PASSWORD
    value: ${DB_PASSWORD}
  - key: DB_NAME
    value: ${DB_NAME} 