name: devroid
services:
  - name: web
    dockerfile_path: Dockerfile
    source_dir: /
    github:
      branch: main
      deploy_on_push: true
      repo: votre-username/devroid
    health_check:
      http_path: /
    instance_count: 1
    instance_size_slug: basic-xs
    envs:
      - key: NODE_ENV
        value: production
      - key: NUXT_PUBLIC_SITE_URL
        value: ${APP_URL}
      - key: CHROMIUM_PATH
        value: /tmp/chromium
    routes:
      - path: / 