name: devunity
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
    repo: nurdjedidi/devunity
  buildpacks:
    - name: digitalocean/nodejs-appdetect
      version: v0.0.6
  build_command: |
    npm install --platform=linux --arch=x64
    npm install --legacy-peer-deps
    npm run build
  run_command: npm run start
  envs:
  - key: NODE_ENV
    value: production 